# Generated by Django 4.2.6 on 2023-11-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('number_of_ratings', models.IntegerField(default=0)),
            ],
        ),
    ]
