# Generated by Django 4.2.6 on 2023-11-14 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_image', models.CharField(max_length=50)),
                ('user_status', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=250)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('number_of_ratings', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
