# Generated by Django 4.2.6 on 2023-11-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooklandAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
