# Generated by Django 4.2.6 on 2023-11-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooklandAPI', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Product',
        ),
    ]
